/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author derekmac
 */
public class VistaPrin extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrin
     */
    public VistaPrin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Registro = new javax.swing.JMenu();
        botonRegistroPasajero = new javax.swing.JMenuItem();
        botonRegistroPiloto = new javax.swing.JMenuItem();
        botonRegistroVuelo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mReserva = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mConsultaVuelo = new javax.swing.JMenuItem();
        mConsultaPiloto = new javax.swing.JMenuItem();
        mConsultaPasajero = new javax.swing.JMenuItem();
        botonSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setToolTipText("");

        Registro.setText("Registro");
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });

        botonRegistroPasajero.setText("Pasajero");
        Registro.add(botonRegistroPasajero);

        botonRegistroPiloto.setText("Piloto");
        Registro.add(botonRegistroPiloto);

        botonRegistroVuelo.setText("Vuelo");
        botonRegistroVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroVueloActionPerformed(evt);
            }
        });
        Registro.add(botonRegistroVuelo);

        jMenuBar1.add(Registro);

        jMenu3.setText("Reservar");

        mReserva.setText("Adquirir Tiquete");
        jMenu3.add(mReserva);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Consultar");

        mConsultaVuelo.setText("Vuelo");
        jMenu2.add(mConsultaVuelo);

        mConsultaPiloto.setText("Piloto");
        jMenu2.add(mConsultaPiloto);

        mConsultaPasajero.setText("Pasajero");
        jMenu2.add(mConsultaPasajero);

        jMenuBar1.add(jMenu2);

        botonSalir.setText("Salir");
        jMenuBar1.add(botonSalir);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroActionPerformed

    private void botonRegistroVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroVueloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Registro;
    public javax.swing.JMenuItem botonRegistroPasajero;
    public javax.swing.JMenuItem botonRegistroPiloto;
    public javax.swing.JMenuItem botonRegistroVuelo;
    public javax.swing.JMenu botonSalir;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem mConsultaPasajero;
    public javax.swing.JMenuItem mConsultaPiloto;
    public javax.swing.JMenuItem mConsultaVuelo;
    public javax.swing.JMenuItem mReserva;
    // End of variables declaration//GEN-END:variables
}
